Connection per label
SDVentures/Contour pull request #13
Opened 2017-02-13 14:41 UTC by semion-akimtsev

This update enables the bus to use a separate connection for each sender and receiver while maintaining the maximum number of connections in the bus.

2017-02-27 09:55 UTC, mzabolotko requested changes

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Transport/RabbitMQ/Internal/IRabbitConnection.cs
> +    internal interface IRabbitConnection : IChannelProvider<RabbitChannel>, IConnection
I am not sure that this correct name of a connection. There is some redunancy I think: 
` Contour.Transport.RabbitMQ.Internal.IRabbitConnection`.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Transport/RabbitMQ/Internal/RabbitConnection.cs
> +        public RabbitConnection(RabbitBus bus)
Why the connection pool does not control a connection timeout and an operation timeout?

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Configuration/BusConfiguration.cs
> +    public class BusConfiguration : IBusConfigurator, IBusConfiguration
There is no need to make the BusConfiguration class as public.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Configuration/BusConfiguration.cs
> +        public void ReuseConnection()
The new instance of the connection will be created every time by default. It does not match with the previous behaviour.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Configuration/EndpointOptions.cs
> +    /// Endpoint options
This comment does not help.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/ConnectionPool.cs
> +                    throw new ObjectDisposedException(nameof(ConnectionPool<TConnection>));
Why do you use nameof(ConnectionPool<TConnection>)?

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/ConnectionPool.cs
> +        public void Drop()
This method needs more logging.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/IBusFactory.cs
> +    public interface IBusFactory
What is the reason of this interface creation?

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/MessageLabelResolver.cs
> +    public class MessageLabelResolver
There is no need to make the MessageLabelResolver class as public.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Serialization/JsonNetPayloadConverter.cs
> +    public class JsonNetPayloadConverter : IPayloadConverter
There is no need to make the JsonNetPayloadConverter class as public.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Transport/RabbitMQ/BusConfigurationEx.cs
> +                ReuseConnection = false
ReuseConnection should be true by default to save old behavior.

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Transport/RabbitMQ/Internal/Listener.cs
> +            this.channel = connection.OpenChannel();
What is a reason to change time when channel will open?

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Transport/RabbitMQ/Internal/ProducerRegistry.cs
> +                    this.bus.ListenerRegistry.ResolveFor(configuration.CallbackConfiguration));
Is there any chance to set a connection string for the callback configuration?

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Transport/RabbitMQ/Internal/RabbitBus.cs
> +            lock (this.logger)
logger???

2017-02-27 09:55 UTC, mzabolotko commented on Sources/Contour/Validation/MessageValidatorRegistry.cs
> +    public class MessageValidatorRegistry
There is no need to make the MessageValidatorRegistry class as public.

2017-02-27 09:55 UTC, mzabolotko commented on Tests/Contour.Configurator.Tests/BusConfigurationSpecs.cs
> +                string Config = $@"<endpoints>
incorrect line ending.

2017-02-27 12:10 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/Internal/RabbitConnection.cs
> +        public RabbitConnection(RabbitBus bus)
This is considered a client's responsibility - an operation on the pool (Get) can be cancelled after a timeout.

2017-02-27 12:11 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +    public class BusConfiguration : IBusConfigurator, IBusConfiguration
Please take a look at https://github.com/SDVentures/Contour/pull/13#commitcomment-21063536

2017-02-27 12:13 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +        public void ReuseConnection()
Clarification needed

2017-02-27 12:15 UTC, semion-akimtsev commented on Sources/Contour/Configuration/EndpointOptions.cs
> +    /// Endpoint options
Will this work? - "Stores the configuration options related to bus endpoint"

2017-02-27 12:17 UTC, semion-akimtsev commented on Sources/Contour/ConnectionPool.cs
> +                    throw new ObjectDisposedException(nameof(ConnectionPool<TConnection>));
Just to specify the name (the name of the type actually) of the object being disposed.

2017-02-27 12:18 UTC, semion-akimtsev commented on Sources/Contour/ConnectionPool.cs
> +        public void Drop()
Clarification needed

2017-02-27 12:21 UTC, semion-akimtsev commented on Sources/Contour/IBusFactory.cs
> +    public interface IBusFactory
IBusFactory has been introduced to describe the common behavior of Bus objects' construction. It is needed to support testing as well.

2017-02-27 12:22 UTC, semion-akimtsev commented on Sources/Contour/MessageLabelResolver.cs
> +    public class MessageLabelResolver
This need has arised after BusConfiguration type has been made public.

2017-02-27 12:23 UTC, semion-akimtsev commented on Sources/Contour/Serialization/JsonNetPayloadConverter.cs
> +    public class JsonNetPayloadConverter : IPayloadConverter
This need has arised after BusConfiguration type has been made public.

2017-02-27 12:25 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/BusConfigurationEx.cs
> +                ReuseConnection = false
Ok

2017-02-27 12:36 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/Internal/Listener.cs
> +            this.channel = connection.OpenChannel();
This change is going to be rolledback because it breaks the listener scaling mechanism.

2017-02-27 14:18 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/Internal/ProducerRegistry.cs
> +                    this.bus.ListenerRegistry.ResolveFor(configuration.CallbackConfiguration));
Yes, currently a callback listener is taken or created in the same way as an ordinary listener, thus its' connection string can be set.

2017-02-27 14:22 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/Internal/RabbitBus.cs
> +            lock (this.logger)
Yes, a hard childhood of Contour. :)
I will fix it.

2017-02-27 14:23 UTC, semion-akimtsev commented on Sources/Contour/Validation/MessageValidatorRegistry.cs
> +    public class MessageValidatorRegistry
This need has arised after BusConfiguration type has been made public.

2017-02-27 14:28 UTC, semion-akimtsev commented on Tests/Contour.Configurator.Tests/BusConfigurationSpecs.cs
> +                string Config = $@"<endpoints>
Should use LF?

2017-02-27 14:47 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/Internal/IRabbitConnection.cs
> +    internal interface IRabbitConnection : IChannelProvider<RabbitChannel>, IConnection
We'll fix such issues in https://github.com/SDVentures/Contour/issues/14

2017-02-27 14:56 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/Internal/RabbitConnection.cs
> +        public RabbitConnection(RabbitBus bus)
We'll fix this in https://github.com/SDVentures/Contour/issues/15

2017-02-27 15:01 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +    public class BusConfiguration : IBusConfigurator, IBusConfiguration
Fixed.

2017-02-27 15:05 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +        public void ReuseConnection()
Fixed.

2017-02-27 15:09 UTC, semion-akimtsev commented on Sources/Contour/Configuration/EndpointOptions.cs
> +    /// Endpoint options
Fixed.

2017-02-27 15:11 UTC, semion-akimtsev commented on Sources/Contour/ConnectionPool.cs
> +                    throw new ObjectDisposedException(nameof(ConnectionPool<TConnection>));
Fixed.

2017-02-27 15:26 UTC, semion-akimtsev commented on Sources/Contour/ConnectionPool.cs
> +        public void Drop()
Fixed.

2017-02-27 15:37 UTC, semion-akimtsev commented on Sources/Contour/IBusFactory.cs
> +    public interface IBusFactory
Fixed.

2017-02-27 15:40 UTC, semion-akimtsev commented on Sources/Contour/MessageLabelResolver.cs
> +    public class MessageLabelResolver
Fixed.

2017-02-27 15:41 UTC, semion-akimtsev commented on Sources/Contour/Serialization/JsonNetPayloadConverter.cs
> +    public class JsonNetPayloadConverter : IPayloadConverter
Fixed.

2017-02-27 16:03 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/Internal/ProducerRegistry.cs
> +                    this.bus.ListenerRegistry.ResolveFor(configuration.CallbackConfiguration));
Need a test for this case to check: receiving using con string 1 and producing requests using con string 2. See https://github.com/SDVentures/Contour/issues/17

2017-02-27 16:05 UTC, semion-akimtsev commented on Sources/Contour/Validation/MessageValidatorRegistry.cs
> +    public class MessageValidatorRegistry
Fixed.

2017-02-27 16:12 UTC, semion-akimtsev commented on Tests/Contour.Configurator.Tests/BusConfigurationSpecs.cs
> +                string Config = $@"<endpoints>
Fixed.

2017-03-01 11:22 UTC, semion-akimtsev commented
@mzabolotko,
updates on review comments have been checked in.
Please take a look at the updated merge request.

2017-03-02 11:15 UTC, mzabolotko approved these changes

2017-03-02 11:18 UTC, merged