Move caching to Contour.Caching
SDVentures/Contour pull request #75
Opened 2017-04-20 08:38 UTC by andrey-prokopyev

2017-06-08 09:38 UTC, semion-akimtsev commented
@andrey-prokopyev ,

could you please provide description of the intent and changes of this pull request?

2017-06-08 11:26 UTC, andrey-prokopyev commented
@semion-akimtsev, done

2017-06-08 12:40 UTC, semion-akimtsev commented
Where Contour.Caching and corresponding tests are located?

2017-06-08 12:42 UTC, semion-akimtsev requested changes
Please make this fork merge-able with the silver-lizard branch.

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/CallbackEndpointElement.cs
> +    public class CallbackEndpointElement : ConfigurationElement
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/EndpointCollection.cs
> +    public class EndpointCollection : ConfigurationElementCollection
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/EndpointElement.cs
> +    public class EndpointElement : ExtensibleConfigurationElement
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/EndpointsSection.cs
> +    public class EndpointsSection : ConfigurationSection
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/IncomingCollection.cs
> +    public class IncomingCollection : ConfigurationElementCollection
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/IncomingElement.cs
> +    public class IncomingElement : MessageElement
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/LambdaDependencyResolver.cs
> +    public class LambdaDependencyResolver : IDependencyResolver
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/MessageElement.cs
> +    public class MessageElement : ExtensibleConfigurationElement
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/OutgoingCollection.cs
> +    public class OutgoingCollection : ConfigurationElementCollection
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/OutgoingElement.cs
> +    public class OutgoingElement : MessageElement
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/ValidatorCollection.cs
> +    public class ValidatorCollection : ConfigurationElementCollection
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour.Configuration/Configurator/ValidatorElement.cs
> +    public class ValidatorElement : ConfigurationElement
Why should this type be public?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +            this.FilterDecorators[typeof(T)] = decorator;
The type of what entity should be used as T?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour/Contour.csproj
> +    <Reference Include="System.Xml" />
Why is this dependency needed?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour/Filters/IMessageExchangeFilterDecorator.cs
> +    using System.Threading.Tasks;
Move the using directive outside the namespace scope.

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour/Filters/IMessageExchangeFilterDecorator.cs
> +    public interface IMessageExchangeFilterDecorator
What types implement this interface?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour/Filters/MessageExchangeFilterInvoker.cs
> +            this.filterDecorators = filterDecorators;
Shouldn't the filterDecorators collection be checked for null here?

2017-06-08 12:42 UTC, semion-akimtsev commented on Sources/Contour/Serialization/JsonNetPayloadConverter.cs
> +    public class JsonNetPayloadConverter : IPayloadConverter
Why should this type be public?

2017-06-09 14:29 UTC, andrey-prokopyev commented
@semion-akimtsev, configuration types must be public because of their extensibility. Side projects should be able to read ExtensionProperties and ExtensionConfigurations. Other internal config elements became public because of their visibility as types of public properties.

2017-06-09 14:29 UTC, andrey-prokopyev commented
@semion-akimtsev, LambdaDependencyResolver became public beacuse of it's use in Contour.Caching

2017-06-09 14:30 UTC, andrey-prokopyev commented
@semion-akimtsev, System.Xml is used in ExtensibleConfigurationElement

2017-06-09 14:31 UTC, andrey-prokopyev commented
@semion-akimtsev, JsonNetPayloadConverter is used in message hasher of Contour.Caching

2017-06-09 14:32 UTC, andrey-prokopyev commented
@semion-akimtsev , Contour.Caching is located at our internal new.git.dev

2017-06-13 08:31 UTC, semion-akimtsev commented on Sources/Contour/Filters/MessageExchangeFilterInvoker.cs
> +            this.filterEnumerator = filters.Reverse().
The IEnumerable collection does not guarantee the order of its elements. What should the correct order be here?

2017-06-13 08:42 UTC, semion-akimtsev commented on Sources/Contour/Filters/IMessageExchangeFilterDecorator.cs
>      public interface IMessageExchangeFilterDecorator
A type which should be used as a decorator must implement an interface of the decorated object per definition. See http://www.oodesign.com/decorator-pattern.html for detailed explanation. The purpose of this is to hide the actual difference between the original object and the augmented one from the consumers of the interface. Why does IMessageExchangeFilterDecorator not do it?

2017-06-13 08:43 UTC, semion-akimtsev reviewed
Please take a look at the comments below.... or above :)

2017-06-13 09:55 UTC, semion-akimtsev commented
@andrey-prokopyev , @mzabolotko ,

I see that we have a couple of changes (types accessibility levels etc.) in Contour which should affect the behavior of some other library which is currently "private". These changes cannot be validated now and we cant justify them because the "other" library is not part of the solution. I suggest that we move Contour.Caching to this repository (not assembly) and make it build-able because despite it should be detached from Contour itself it is still a part of it as a framework. Or rename the library to something_cool_not_referencing_contour.Caching and make it dependent on the branch of Contour project.

2017-06-22 12:20 UTC, andrey-prokopyev commented
@mzabolotko, so Contour.Caching should be separate repository or separate project in Contour repo?

2017-07-11 14:12 UTC, closed without merging