Added ability to set excluded incoming message headers from copying t…
SDVentures/Contour pull request #91
Opened 2017-06-13 15:21 UTC by bullmastiffo

…o outgoing messages

2017-06-13 15:28 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +﻿using Contour.Transport.RabbitMQ;
There should be no transport specific references here.

2017-06-13 15:29 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +        public IEnumerable<string> ExcludedIncomingHeaders { get; private set; }
What is the configuration scope of this setting?
If it is Endpoint then it needs to be moved to EndpointOptions etc.

2017-06-13 15:36 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +        public IEnumerable<string> ExcludedIncomingHeaders { get; private set; }
I suggest that it should be renamed to ExcludeHeaders.

2017-06-13 15:42 UTC, semion-akimtsev commented on Sources/Contour/Configuration/IBusConfiguration.cs
> +        IEnumerable<string> ExcludedIncomingHeaders { get; }
This should be moved to EndpointOptions, SendersDefaults or ReceiverDefaults.

2017-06-13 15:45 UTC, semion-akimtsev commented on Sources/Contour/Configuration/IBusConfigurator.cs
> +        void SetExcludedIncomingHeaders(IEnumerable<string> excludedHeaders);
This change should be made according to the scope of the ExcludeHeaders property.

2017-06-13 15:50 UTC, semion-akimtsev commented on Sources/Contour/Configurator/EndpointElement.cs
> +        public IEnumerable<string> ExcludedHeaders
This type is not responsible for string operations. It should only read the configuration. This should be moved to a place where a list of headers is obtained from the configuration property.

2017-06-13 15:53 UTC, semion-akimtsev commented on Sources/Contour/Transport/RabbitMQ/BusConfigurationEx.cs
> +            var messageHeaderStorage = new Maybe<IIncomingMessageHeaderStorage>(new MessageHeaderStorage(blockedHeaders));
Maybe is obsolete.

2017-06-13 15:55 UTC, semion-akimtsev commented on Tests/Contour.Configurator.Tests/BusConfigurationSpecs.cs
> +        public class c_with_parallelism_level
?

2017-06-13 15:55 UTC, semion-akimtsev reviewed
Please review the comments.

2017-06-13 16:14 UTC, bullmastiffo commented on Sources/Contour/Configuration/BusConfiguration.cs
> +﻿using Contour.Transport.RabbitMQ;
moved

2017-06-13 16:14 UTC, bullmastiffo commented on Sources/Contour/Configuration/BusConfiguration.cs
> +        public IEnumerable<string> ExcludedIncomingHeaders { get; private set; }
removed setting

2017-06-13 16:14 UTC, bullmastiffo commented on Sources/Contour/Configuration/BusConfiguration.cs
> +        public IEnumerable<string> ExcludedIncomingHeaders { get; private set; }
removed setting

2017-06-13 16:15 UTC, bullmastiffo commented on Sources/Contour/Configuration/IBusConfiguration.cs
> +        IEnumerable<string> ExcludedIncomingHeaders { get; }
removed setting

2017-06-13 16:16 UTC, bullmastiffo commented on Sources/Contour/Configuration/IBusConfigurator.cs
> +        void SetExcludedIncomingHeaders(IEnumerable<string> excludedHeaders);
There's no scope for endpoint configuration, this improvement is not a subject to change endpoint configuration

2017-06-13 16:17 UTC, bullmastiffo commented on Sources/Contour/Configurator/EndpointElement.cs
> +        public IEnumerable<string> ExcludedHeaders
It's only reading properties. No extra operations. String operations are required to manage serialization used in this config section.

2017-06-13 16:17 UTC, bullmastiffo commented on Tests/Contour.Configurator.Tests/BusConfigurationSpecs.cs
> +        public class c_with_parallelism_level
oops, fixed

2017-06-13 17:01 UTC, mzabolotko commented on Sources/Contour/Configuration/BusConfiguration.cs
> +            this.SenderDefaults.IncomingMessageHeaderStorage = messageHeaderStorage;
I believe the SetExcludedIncomingHeaders method is not right place to set  MessageHeaderStorage. Maybe replace this by the existing method WithIncomingMessageHeaderStorage using overload version with extra parameter 'blockingHeaders'?

2017-06-13 17:44 UTC, bullmastiffo commented on Sources/Contour/Configuration/BusConfiguration.cs
> +            this.SenderDefaults.IncomingMessageHeaderStorage = messageHeaderStorage;
adding to storage through interface method

2017-06-14 06:41 UTC, semion-akimtsev commented on Sources/Contour/Configuration/IBusConfigurator.cs
> +        void SetExcludedIncomingHeaders(IEnumerable<string> excludedHeaders);
Endpoint, incoming and outgoing settings represent the corresponding configuration scopes.

2017-06-14 06:42 UTC, semion-akimtsev commented on Sources/Contour/Configurator/EndpointElement.cs
> +        public IEnumerable<string> ExcludedHeaders
Reading DOES NOT involve processing and splitting a string.

2017-06-14 06:44 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +            var blockedHeaders = (excludedHeaders ?? Enumerable.Empty<string>()).ToArray();
What's the difference between blocked and excluded?

2017-06-14 06:44 UTC, semion-akimtsev commented on Sources/Contour/Configuration/BusConfiguration.cs
> +            var strg = this.SenderDefaults.GetIncomingMessageHeaderStorage();
Are all the vowels gone?

2017-06-14 06:48 UTC, semion-akimtsev commented on Sources/Contour/IIncomingMessageHeaderStorage.cs
> +        void RegisterExcludedHeaders(IEnumerable<string> headers);
The storage is supposed to store and load. If some headers need to be excluded they should be passed via constructor.

2017-06-14 06:57 UTC, semion-akimtsev commented on Sources/Contour/Configurator/EndpointElement.cs
> +        [ConfigurationProperty("excluded-headers")]
excludedHeaders

2017-06-14 06:59 UTC, semion-akimtsev commented on Tests/Contour.Configurator.Tests/BusConfigurationSpecs.cs
> +            public void should_set_excluded_headers()
What is the SUT here?

2017-06-14 07:04 UTC, semion-akimtsev requested changes
Please make the changes and resubmit.

2017-06-14 08:11 UTC, bullmastiffo commented on Sources/Contour/Configurator/EndpointElement.cs
> +        public IEnumerable<string> ExcludedHeaders
Reading settings DOES

2017-06-14 09:49 UTC, semion-akimtsev commented on Tests/Contour.Common.Tests/MessageHeaderStorageSpecs.cs
> +                sut.RegisterExcludedHeaders(excludedListAddition);
This should be validated separately.

2017-06-14 09:50 UTC, semion-akimtsev approved these changes

2017-06-14 09:53 UTC, merged

2017-06-19 09:44 UTC, semion-akimtsev commented
@bullmastiffo @mzabolotko 

Hi guys,
just to notify you - I have made a minor change to the sender and receiver options to support explicit message storage configuration on the endpoint and its propagation to the Rabbit specific defaults. See the commit below https://github.com/SDVentures/Contour/commit/c7cadc07152afef8cde541fa10cbe9633b0ef6ef.

Please do not hesitate to post questions and concerns.